theme: jekyll-theme-hacker

# Site
title: Resume Rex
english-name: Rex Liu
chinese-name: 劉晁維
description: 喜歡貓, 單寧, 美式風格, 金屬樂.
logo: ./images/me.jpg
locale: zh_TW
location: Neihu/Taipei, Taiwan.
blog: https://watain666.github.io

# Google Analytics
# google-analytics:

# Social Links
email: watain666666@gmail.com
github: watain666
linkedin: tiâu-uî-lâu-aab963141
twitter: TiauUILau
facebook: watain666
instagram: doordie666

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/