theme: jekyll-theme-minimal

# Site
title: Resume
taioan-name: Lâu TiâuÛi
chinese-name: 劉晁維
english-name: Rex
description: 喜歡吸收新知識<br>享受透過程式解決各種挑戰獲得的成就感
# logo: ./images/me.jpg
locale: zh_TW
location: Taipei, Taiwan.
blog: https://tiaui.co

# Google Analytics
# google-analytics: UA-101482320-2

# Social Links
email: watain666666@gmail.com
github: watain666
# linkedin: tiâu-uî-lâu-aab963141
# twitter: TiauUILau
# facebook: watain666
# instagram: doordie666

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
